package org.edgeleap.networks;

public enum InteractionType {
	// PathwayCommons SIF mappings
	IN_SAME_COMPONENT,
	METABOLIC_CATALYSIS,
	REACTS_WITH,
	CO_CONTROL,
	INTERACTS_WITH,
	STATE_CHANGE,
	
	// Custom types
	TRANSPORT,
	MEDIATES_INTERACTION,
	IN_GROUP,
	STIMULATION,
	INHIBITION,
	BINDING,
	CLEAVAGE,
	NEGATIVE_EFFECT,
	NEGATIVE_CORRELATION,
	POSITIVE_CORRELATION,
	COMPOSED_OF,
	RECEPTOR_BINDING
	;
}